const users = [
  {
    token:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoiZW1la2FvZmU2QGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkVtZWthIiwibGFzdE5hbWUiOiJPZmUiLCJwYXNzd29yZCI6Im1hdGhzMTAyIiwiYWRkcmVzcyI6Ijc1LCBCb2RlIFRob21hcyBTdHJlZXQifSwiaWF0IjoxNTU2Mzg0Mzk0LCJleHAiOjE1NTg0NTc5OTR9.edYzbdOHaBLrO-QJhBgf9LGCqp3W-DOTK_F6O8ItSR8',
    id: 1,
    email: 'emekaofe16@gmail.com',
    firstName: 'emekaofe',
    lastName: 'Ofe',
    password: '$2a$10$LyDwLEIRU6vmRL8pOgXcF.ZBHi3Mn47i8LUZM3c9rs9W4RplOlFZa',
    address: '13, Bode Thomas Street',
    status: 'unverified',
    isAdmin: false,
  },
  {
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoyLCJlbWFpbCI6ImFkbWluQHF1aWNrLWNyZWRpdC5jb20iLCJzdGF0dXMiOiJ1bnZlcmlmaWVkIiwiaXNBZG1pbiI6ZmFsc2V9LCJpYXQiOjE1NTYzODM4MjksImV4cCI6MTU1ODQ1NzQyOX0.cMhdRlc9gbN_l4ML2WayduDd-Yv6E1mF1lmEXif14dI',
    id: 2,
    email: 'admin@quick-credit.com',
    firstName: 'Emeka',
    lastName: 'Ofe',
    password: '$2a$10$mK7n3hywRroZwq3THuiJ9ewAcIRTQayk3mz0TGl2KHaQ2T5bbYimy',
    address: '75, Bode Thomas Street',
    status: 'unverified',
    isAdmin: false,
  },
  {
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozLCJlbWFpbCI6ImVtZWthb2ZlMjJAZ21haWwuY29tIiwic3RhdHVzIjoidW52ZXJpZmllZCIsImlzQWRtaW4iOmZhbHNlfSwiaWF0IjoxNTU2Njg4NzUxLCJleHAiOjE1NTg3NjIzNTF9.O1mTiHYk_qDA6BIDQjwpqOK9lMckCisQlgmXhdoGZaI',
    id: 3,
    email: 'emekaofe22@gmail.com',
    firstName: 'Emeka',
    lastName: 'Ofe',
    password: '$2a$10$a6NcubTZ6a8GK2X2hailHOqT0JNPy2dP65xnx8HA/7DZ1ZQBJxLtq',
    address: '75, Bode Thomas Street',
    status: 'unverified',
    isAdmin: false,
  },
  {
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjo0LCJlbWFpbCI6ImVtZWthb2ZlMjFAZ21haWwuY29tIiwic3RhdHVzIjoidW52ZXJpZmllZCIsImlzQWRtaW4iOmZhbHNlfSwiaWF0IjoxNTU2NjkwMDkzLCJleHAiOjE1NTg3NjM2OTN9.s7ASDpJI4dU6mlBVaZZ3A8zsW8ksexpOg_vxzPdpcK4',
    id: 4,
    email: 'emekaofe21@gmail.com',
    firstName: 'Emeka',
    lastName: 'Ofe',
    password: '$2a$10$FVLuy.K.J647CADNUaoU.ew9TWsDw1cFH6.s/hi2xcoZreZXNmQc.',
    address: '75, Bode Thomas Street',
    status: 'unverified',
    isAdmin: false,
  }, {
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjo1LCJlbWFpbCI6ImVtZWthb2ZlMThAZ21haWwuY29tIiwic3RhdHVzIjoidW52ZXJpZmllZCIsImlzQWRtaW4iOmZhbHNlfSwiaWF0IjoxNTU3MDc4MzcwLCJleHAiOjE1NTkxNTE5NzB9.0rpyamb75Wa9AEd-BEdjQV4ZHlJ7vnm4ko1KzZcfGc4',
    id: 5,
    email: 'emekaofe18@gmail.com',
    firstName: 'Emeka',
    lastName: 'Ofe',
    password: '$2a$10$Lqrs/fyeuH8AYGtl.cUe8egPNohxjSdallGjTKKdqgqqJiZU.FS2.',
    address: '75, Bode Thomas Street',
    status: 'verified',
    isAdmin: false,
  },
];

export default users;
